# Generated by Django 3.1.4 on 2021-01-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
